### ISSUE TITLE
Problem to record new number

### ISSUE THREAD

**Issue by Pudins** [venomous0x/WhatsAPI#1080]
I can not register a new number? Says he hears a problem in the request and asked to return in an hour! Some functional alternative?

**Comment by diegodalbosco** [comment]
I have the same problem

**Comment by Pudins** [comment]
Is difficult the solution

**Comment by diegodalbosco** [comment]
I migrated to https://github.com/mgp25/WhatsAPI-Official and I have the same problem. Is there a solution?

**Comment by mgp25** [comment]
Post code and debug log in whatsapi official describimg your issue, and we will find out the issue

Regards

**Comment by Pudins** [comment]
@mgp25 My problem is precisely {"status": "fail", "reason": "no_routes", "retry_after": 3600}, there is already a solution?

**Comment by mgp25** [comment]
@Pudins check WhatsAPI Official repo, this one is inactive and not updated.

https://github.com/mgp25/WhatsAPI-Official

**Comment by Pudins** [comment]
First I'm sorry for the delay! Now yes this all working perfectly. Grateful for your help @mgp25
