### ISSUE TITLE
Problems sending video!

### ISSUE THREAD

**Issue by Pudins** [venomous0x/WhatsAPI#1081]
Hello people!
I'm having trouble sending video by api anyone have any tips?
How do I find the hash?

**Comment by mgp25** [comment]
This repo is inactive, go to https://github.com/mgp25/WhatsAPI-Official instead

In the wiki is an example and you can use the event to store it

Regards

**Comment by Pudins** [comment]
Agora sim esta tudo funcionando perfeitamente. Grato pela sua ajuda @mgp25

**Comment by Pudins** [comment]
Now yes this all working perfectly. Grateful for your help @mgp25
