### ISSUE TITLE
How to check the valid whatsapp number before sendmessage?

### ISSUE THREAD

**Issue by techcare2u** [venomous0x/WhatsAPI#1094]
Hi..I am new here also new to php..i can sendmessage and use contactsync but i don't know how to combine this 2. I am prefer function onSyncResult can send a true or false before i start sendmessage. Any guru can help me? thanks a lot

**Comment by mgp25** [comment]
@techcare2u this repo is inactive, Use this one instead: https://github.com/mgp25/WhatsAPI-Official

There is a wiki too: https://github.com/mgp25/WhatsAPI-Official/wiki

And many examples: https://github.com/mgp25/WhatsAPI-Official/tree/master/examples

Regards

**Comment by techcare2u** [comment]
Thank you :)
