### ISSUE TITLE
My registered number was blocked

### ISSUE THREAD

**Issue by cfathoni** [venomous0x/WhatsAPI#1116]
Hi,

I have used whatsapi for a week without a problem. But, today when I tried to start my application it always throw whatsappException which means fail to login. Then I tried to use the registered number on my phone but when I try to connect the number, the message "Your number is no longer allowed" occurred, that means my number was blocked. I do not use it for sending bulk message. So could you help me what makes the number to be blocked by Whatsapp. Btw, when I tried to register other number it works normally. Thanks for your help

**Comment by mgp25** [comment]
@cfathoni WhatsApp only blocks spammers and people who abuse their system.

This repo is inactive, use this instead: https://github.com/mgp25/WhatsAPI-Official

Regards
