### ISSUE TITLE
is there any help video or can any body help me using that ??

### ISSUE THREAD

**Issue by kokoalawi** [venomous0x/WhatsAPI#1130]
i dont know what can i do after i download the zip file

**Comment by mgp25** [comment]
Use WhatsAPI Official: https://github.com/mgp25/WhatsAPI-Official

All info here: https://github.com/mgp25/WhatsAPI-Official/wiki

**Comment by kokoalawi** [comment]
I need video or something like that ....... because when i request code i get nothing ............, can i get the software is completed ....

**Comment by mgp25** [comment]
@kokoalawi its everything explained there, including the tools: https://github.com/mgp25/WhatsAPI-Official/wiki

**Comment by kokoalawi** [comment]
Thanks a lot , i found it ..
