### ISSUE TITLE
congrats every one api ver. changed

### ISSUE THREAD

**Issue by sadiqhirani** [venomous0x/WhatsAPI#1145]
hey all
today this fine morning when i started to test the code which i developed with the help of whatsapi/chat-api
i found that v2 stopped registrations and new devices
and then i manually checked v.whatsapp.net/v3/ url... and i found that new ver of api is being applied (means v2 not fully stopped but some features of v2 are stopped)

**Comment by catch2patch** [comment]
Hey :) And what about http://v.whatsapp.net/v4/ http://v.whatsapp.net/v5/
http://v.whatsapp.net/v6/ etc? )

2015-05-25 8:46 GMT+03:00 sadiqhirani notifications@github.com:

**Comment by sadiqhirani** [comment]
i didn't checked that but while i was testing v2 i got error in registering number i got response
{"status" : "fail" , "reason" : "old_version"}
i used both methods sms as well as voice

**Comment by catch2patch** [comment]
I mean if you open v2, v3 and also v4, v5 in the browser, it will show a page and ask to download the app.
How did you check if v3 really works?
Did it stop throwing "old_version" with v3?

**Comment by sadiqhirani** [comment]
i just mean to say that v2 will be no more (very soon)

**Comment by mgp25** [comment]
registrations still works, and this issue makes really no sense.

You are opening a issue in an inactive repository, and then you havent realized that the problem is that you havent updated your code to latest version or even WhatsApp have blocked your server

Proof:

```
Array
(
    [in] => number
    [cc] => 34
w|?????] => ???kb\?
    [lg] => es
    [lc] => ES
    [sim_mcc] => 214
    [sim_mnc] => 000
    [method] => sms
    [token] => 1289f***c80c1***3350416***53a***
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => sms
    [retry_after] => 1805
)
```

Biggest facepalm ever!

**Comment by sadiqhirani** [comment]
ok thanks bro...
by the way there are much resps which are distributing same and same stuffs so i got a bit wired but thanks now i will update my resp.
