### ISSUE TITLE
Is there any why to check if number added me to list contacts?

### ISSUE THREAD

**Issue by adams99** [venomous0x/WhatsAPI#1178]
I want to check if number added me to list contacts before sending message, I have now only sync new contact before sending message.
I send message to only subscriptions numbers. 
User himself can subscrip to get news from my site, I am using whatsAPI to send messages.

**Comment by mgp25** [comment]
Use: https://github.com/WHAnonymous/Chat-API

It's explained in the wiki

Regards

**Comment by adams99** [comment]
Thank to replay. But I cant find any thing like this issue un the wiki.may be you didnt uderstand me. I want to detect if account whatsapp with number  user subscription added my sender number to list contacts.

**Comment by mgp25** [comment]
@adams99 is not possible

**Comment by adams99** [comment]
Thanks.
