### ISSUE TITLE
Login broken

### ISSUE THREAD

**Issue by zstars** [venomous0x/WhatsAPI#126]
Login seems to be broken once again. Might be the somewhat frequent two-magic-bytes change, or something more shady.

**Comment by avdeshkataria** [comment]
Hi,
I'm developing the .net application to send mesages using Whatsapp api (version 15.4.29(https://www.nuget.org/packages/WhatsAppAPI/)).
I generate the password of sender using WART.
2 months back, the code was working and able to send messages. but suddenly its stopped working. Now i'm getting "Not - Authorized" error while log in.
Code :

---

 WhatsApp wa = new WhatsApp(sender1, password, "ajcfday", true);
                // wa.Login();
                wa.OnConnectSuccess += () =>
                {
                    wa.OnLoginSuccess += (phoneNumber, data) =>
                    {
                        wa.SendMessage(rcvr/\* Number */, mainMessage);
                        result = result + Environment.NewLine + "Sender: " + sender1 + "--- Message Sent";
                    };

```
                wa.OnLoginFailed +=
                    (data) =>
                    {
                        result = result + Environment.NewLine + "Sender: " + sender1 + "--- Result ----> "+ data;
```

//"Not - Authorized" Error is Coming here   <--------------------------------------
                           // MessageBox.Show(data);
                        };
                    wa.Login();
                };
                string sender2 = sender1;
                wa.OnConnectFailed += (ex) =>
                {
                   // MessageBox.Show(ex.Message);
                    result = result + Environment.NewLine + "Sender: " + sender2 + "--- Exception occur ----> " + ex.Message;
                };
                wa.Connect(); 

---

Please help...................

**Comment by gmonte** [comment]
login 'not-authorized' exception. why??
Whats.OnLoginSuccess += (phoneNumber, data) =>
                        {
                            Whats.SendMessage(to, msg);
                            Console.WriteLine("Enviando mensagem...");
                        };
                        Whats.OnLoginFailed += (data) =>
                        {
                            MessageBox.Show("login falhou: " + data);
                        };
                        try
                        {
                            Whats.Login();
                        }
                        catch (Exception er)
                        {
                            MessageBox.Show("login falhou: " + er.ToString());
                        }
