### ISSUE TITLE
Whatsapp server closing connection to the script

### ISSUE THREAD

**Issue by eslamo** [venomous0x/WhatsAPI#135]
[] Listen mode:
PHP Warning:  socket_read(): unable to read from socket [0]: An established connection was aborted by the software in your host machine. in C:\wamp\www\whatsapp\whatsprot.class.php on line 140

Line 140: $ret = socket_read( $this->_socket, 1024 );

I think they changed the way of the connection and they drop script connection

**Comment by narasimha6666** [comment]
Hi... 
I am getting "An established connection was aborted by the software in your host machine", please let me know how to solve this issue.
