### ISSUE TITLE
Any one knows the whatsapp sending limit for each account?

### ISSUE THREAD

**Issue by bjdudu** [venomous0x/WhatsAPI#248]
I sent about 300 messages in 12 hours, and got blocked.

**Comment by skydevelopers** [comment]
if you send 500 messages per day, with not more than 50 message in one go, there are very few chances of getting blocked, if you are looking for a way to send bulk message to whatsapp contact me [here](https://www.skydevelopers.net). I can tell you the easiest ways / tricks to send free bulk message.
