### ISSUE TITLE
Problem in requestCode

### ISSUE THREAD

**Issue by eslamo** [venomous0x/WhatsAPI#322]
Hi all .. my country is Kuwait and i our Country code is 965 and our language is arabic

what should this line format be ??

$w->requestCode('sms', 'ES', 'es');

cause i always have this error
WhatsProt->requestCode('sms', 'ES', 'es') #1 {main} thrown in C:\Inetpub\whatsapi\whatsprot.class.php on line 1174

i tried to modify it to requestCode('sms', 'KW', 'ar') and i have the same error here

**Comment by Davit21** [comment]
I have an error
Call to undefined method WhatsProt::requestCode()
who can help me

**Comment by mgp25** [comment]
@Davit21 Use WhatsAPI Official: https://github.com/mgp25/WhatsAPI-Official

Wiki: https://github.com/mgp25/WhatsAPI-Official/wiki
