### ISSUE TITLE
There is a problem in requestCode which always return sent or fail

### ISSUE THREAD

**Issue by ahmadabudawod** [venomous0x/WhatsAPI#337]
I have try to request code many time but still get fail or sent as the following below ,is there any one face this problem in PHP API:
[status] => fail [reason] => too_recent [retry_after] => 24936

**Comment by darshanadhia1** [comment]
this doesnot work even by changing differnet user agents
is this api still working?

**Comment by anthonymcg22** [comment]
What is the most up to date useragent and token?

**Comment by Subhajit321** [comment]
WART is not working
![image](https://user-images.githubusercontent.com/39081525/42364087-99cfe6d2-8117-11e8-8138-34114d7e8511.png)
Please help me
