### ISSUE TITLE
sending image/video not working

### ISSUE THREAD

**Issue by murad1981** [venomous0x/WhatsAPI#338]
in Examples.php file I try to send an image with this line:
$w->MessageImage($destinationPhone, 'http://questgarden.com/84/77/7/090712062416/images/Purple%20Mountain%20Magesties.jpg');

and a video file with this line:

$w->MessageVideo($destinationPhone, 'http://dl.dropboxusercontent.com/u/57066689/video1.mp4');

each at a time, but nothing happens in the browser more than the following echo statements of the examples.php file: 

start connect

tx tx tx tx rx rx rx rx rx #N�`��+F���W~$v� tx �� ��6���@������2�{�A����|p���_T�-h�0{��X��$ rx "k�0O�S�y���钙�x�� tx 

end connect

Start login

End login

giving that text messages work fine. 

the image is small and you can review it in your browser, the mp4 video is ~20MB in size.

I saw some old similar issues, but they did not solve the problem !!! 
do these features really work or not ?

**Comment by bernabegh** [comment]
Hi @shirioko 
Im getting some problems when i try to send an image.
This is the debug result and the errors from PHP.
do u know some solution ?
![screen shot 2015-11-12 at 11 43 52 am](https://cloud.githubusercontent.com/assets/4949875/11126062/ccf79968-8932-11e5-991f-9b1b13fea5ff.png)
