### ISSUE TITLE
broadcast a text message to multiple phone numbers

### ISSUE THREAD

**Issue by murad1981** [venomous0x/WhatsAPI#348]
is it possible to use this api to broadcast a text message to multiple phone numbers ? if yes, please show an example for its usage.

thanks in advance.

**Comment by Davit21** [comment]
Hi,i want send broadcast message
this code does not show error but message was not sent

$targets = array("number",'number');
$w->sendBroadcastMessage($targets, $message);
$w->pollMessage();

**Comment by mgp25** [comment]
@Davit21 this repo is inactive, ask and use in WhatsAPI Official repo

WhatsAPI Official: https://github.com/mgp25/WhatsAPI-Official

Regards
