### ISSUE TITLE
bad_token?

### ISSUE THREAD

**Issue by Pietertje007** [venomous0x/WhatsAPI#349]
I am trying to register a brandnew sim in my phone that I use all the time. Im running MissVenom to sniff all the trafic. Phone just updated to Cyanogen 10. 

trace from missVenom:

REQUEST:  https:// v.whatsapp.net/v2/code?cc=32&in=9xxxxxxxx&id=abcdef0123456789&lg=nl&lc=NL&mnc=004&mcc=204&method=sms&reason=self-send-jailbroken&token=049890c2XX7f14526XX7560058e4cec3
RESPONSE: {"status":"fail","reason":"bad_token"}

REQUEST:  https:// v.whatsapp.net/v2/code?cc=32&in=9xxxxxxxx&id=abcdef0123456789&lg=nl&lc=NL&mnc=004&mcc=204&method=voice&reason=server-send-request-bad-token&token=049890c2XX7f14526XX7560058e4cec3
RESPONSE: {"status":"fail","reason":"bad_token"}

Anyone any ideas about this?
Is the token linked to the phone and blocked by whatsapp? Or has it to do with my custom firmware that causes a self-send-jailbroken in the request?

**Comment by kaank** [comment]
Hi,

Please change this class in whatsappapi.dll 

  class WaToken {
        public static string GenerateToken(string number) {
            string s = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1430860548912" + number;
            byte[] bytes = Encoding.ASCII.GetBytes(s);
            byte[] value = MD5.Create().ComputeHash(bytes);
            return BitConverter.ToString(value).Replace("-", string.Empty).ToLower();
        }
        private static List<byte> GetFilledList(byte item, int length) {
            List<byte> list = new List<byte>();
            for (int i = 0; i < length; i++) {
                list.Add(item);
            }
            return list;
        }
    }

Kaan Karataç

**Comment by Subhajit321** [comment]
not working. shows bad token. please help
![image](https://user-images.githubusercontent.com/39081525/42380204-b37cc2a2-814a-11e8-9e94-3e560a07e59a.png)
