### ISSUE TITLE
The password of certificate when using MissVenom

### ISSUE THREAD

**Issue by elwin0214** [venomous0x/WhatsAPI#399]
Hi
 I am trying to get the password of whatsapp in IOS by MissVenom. I do this work by the guide https://github.com/shirioko/MissVenom, but it prompt  the password entry of certificate when installing.I do not know the password.

And i install the certificate by the link (https://github.com/shirioko/MissVenom/blob/master/MissVenom/all.whatsapp.net.pfx?raw=true) which from the  issues 365(https://github.com/venomous0x/WhatsAPI/issues/365).

**Comment by yoavavram** [comment]
hey,im trying to use missvenom but its sends a "socket error"..(im using windows,nexsus 4 android 4.4.4 kitkat),can you plese help me?

**Comment by fjrmaulana** [comment]
am i late getting whatsappApi
