### ISSUE TITLE
Best way to keep connected and polling messages

### ISSUE THREAD

**Issue by nachourpi** [venomous0x/WhatsAPI#400]
Hi! I have been trying the API and it works very good. However as it doesn't has a manual, I was trying different ways of keeping my client connected in order to get the messages.

The thing is, as it runs as a PHP script, usually PHP is not prepared for being executed continuously, so what's the idea behind this api in order to get the messages if we don't have a sort of interruption or callback mechanism ?
Shall i execute my script every T priods of times and check if I have received something?, like a polling request ?

Shall i configure my web server in order to allow infinite amount of execution time of the scripts and keeps my PHP get messages executing all the day ?

Thanks!

NAcho

**Comment by transonly** [comment]
Well, i'm having great difficulty to keep the script running. In my situation the script listens for $_POST that it receives through an ajax-call like so:
<?php
set_time_limit(0); 
$destinationPhone = $_POST['target'];
$message =  $_POST['message'];
date_default_timezone_set('Europe/Amsterdam');

$w = new WhatsProt($userPhone, $token, $nickname, false);
$w->eventManager()->bind("onGetImage", "GetImage");
$w->connect();
$w->LoginWithPassword($password);
if(isset($destinationPhone)) {
$w->sendSetProfilePicture("ToWa.jpg");
$w->sendMessage($destinationPhone, $message);
}
while (true) {
    while($w->pollMessage());
 $w->getMessages();
}
function GetImage($mynumber, $from, $id, $type, $time, $name, $size, $url, $file, $mimetype, $filehash, $width, $height, $preview){
//some imageprocessing
}
?>

The script responds well to the ajaxcall but eventually it does NOT respond anymore to the onGetImage function when someone sends a photo.
Can you help me with that?

**Comment by transonly** [comment]
Allredy solved it by sending dummy message every minute via nodejs server i've running.

**Comment by mgp25** [comment]
@transonly use https://github.com/WHAnonymous/Chat-API
