### ISSUE TITLE
not-authorized when trying to login

### ISSUE THREAD

**Issue by AmirGolan85** [venomous0x/WhatsAPI#421]
hey, I used WhatsAPI for some days and everything worked, 
but suddenly today when i try to connect i get the respone from the server:

rx  failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl
rx    not-authorized not-authorized
rx  "failure

anyone got an idea how to fix it?

**Comment by avdeshkataria** [comment]
Hi,
I'm Whatsapp api version 15.4.29(https://www.nuget.org/packages/WhatsAppAPI/).
I generate the password of sender using WART.
2 months back, the code was working and able to send messages. but suddenly its stopped working. Now i'm getting "Not - Authorized" error while log in.
Code :

---

 WhatsApp wa = new WhatsApp(sender1, password, "ajcfday", true);
                // wa.Login();
                wa.OnConnectSuccess += () =>
                {
                    wa.OnLoginSuccess += (phoneNumber, data) =>
                    {
                        wa.SendMessage(rcvr/\* Number */, mainMessage);
                        result = result + Environment.NewLine + "Sender: " + sender1 + "--- Message Sent";
                    };

```
                wa.OnLoginFailed +=
                    (data) =>
                    {
                        result = result + Environment.NewLine + "Sender: " + sender1 + "--- Result ----> "+ data;
```

//"Not - Authorized" Error is Coming here   <--------------------------------------
                           // MessageBox.Show(data);
                        };
                    wa.Login();
                };
                string sender2 = sender1;
                wa.OnConnectFailed += (ex) =>
                {
                   // MessageBox.Show(ex.Message);
                    result = result + Environment.NewLine + "Sender: " + sender2 + "--- Exception occur ----> " + ex.Message;
                };
                wa.Connect(); 

---

Please help................... 
My email is is : avdeshkataria@gmail.com

**Comment by fa-deve** [comment]
i have same problem 
i used this api   https://github.com/mgp25/Chat-API-NET
and not-authorized when trying to login 
 ???

**Comment by Floy2000** [comment]
i have same problem too
Please help)
admin@kgti.ru

**Comment by VivekSingh573** [comment]
Any one can send the WhatsAppAPI.dll   new version, 

because i have API problem, i sent the image , audio and video from my C# code . but today (04/Dec/2015) morning its not orking

**Comment by rameshrdev** [comment]
How to fix these
when login  'LoginFailureException' not-authorized 
How to register using exampleRegister.php or registerTool.php
Before register code required or after it.

This api currently working or not

**Comment by srburton** [comment]
april / 2016  working ?

**Comment by VivekSingh573** [comment]
WART IS NOT WORKING
