### ISSUE TITLE
WP7 token register: old_version

### ISSUE THREAD

**Issue by AmirGolan85** [venomous0x/WhatsAPI#423]
Hey, i tried to register after my first account got blocked and got this messaeg from the server:

stdClass Object
(
    [status] => fail
    [reason] => old_version
)

I changed back to Android Token and it worked..
So please update the API or fix the WP7 token..
Thanks :)

**Comment by shahidkarimi** [comment]
Why I am getting this response:
Array ( [cc] => 92 [in] => 3129912287 [id] => gwo™9}ºw¡a+µð [lg] => en [lc] => PK ) stdClass Object ( [status] => fail [reason] => old_version )

**Comment by jonnywilliamson** [comment]
@shahidkarimi  More interesting is why you posted here, on a closed issue, over 2 1/2 years old, on a github repo that has been deleted!
