### ISSUE TITLE
old version and bad token

### ISSUE THREAD

**Issue by manufuentescr** [venomous0x/WhatsAPI#437]
I try to register an account but when running

$ w-> codeRequest ('SMS');

I get 'old version'

I have changed the constant to the current client version of whatsapp

but I get 'bad token'

Anyone have a token that works with the new version of the client

**Comment by kaank** [comment]
Hi,

Please change this class in whatsappapi.dll 

  class WaToken {
        public static string GenerateToken(string number) {
            string s = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1430860548912" + number;
            byte[] bytes = Encoding.ASCII.GetBytes(s);
            byte[] value = MD5.Create().ComputeHash(bytes);
            return BitConverter.ToString(value).Replace("-", string.Empty).ToLower();
        }
        private static List<byte> GetFilledList(byte item, int length) {
            List<byte> list = new List<byte>();
            for (int i = 0; i < length; i++) {
                list.Add(item);
            }
            return list;
        }
    }

Kaan Karataç
