### ISSUE TITLE
Whatsapp API integration

### ISSUE THREAD

**Issue by sumitraghav** [venomous0x/WhatsAPI#439]
Hello,

I creating a web application for whatsapp in php. I am integrating <a href="https://github.com/venomous0x/WhatsAPI" target="_blank">WhatsAPI</a>. I spent almost 4 hours to understand the api code.But no output. 
Please anybody provide me the steps to start the process.

Thanks in advance.

**Comment by ganesh002** [comment]
hello there
I am also try to integrating whats up in php 
and i had try this to download .exe file but it says 404 error 
https://github.com/shirioko/WART
help me please thanks.
