### ISSUE TITLE
Unexpected '[' in whatsprot.class.php on line 1694

### ISSUE THREAD

**Issue by slobo42** [venomous0x/WhatsAPI#448]
Hello,

I am a new user and wanted to use WhatsAPI, I did several 'git clone' to see if the issue was from a network problem or not. I always get "PHP Parse error:  syntax error, unexpected '[' in /srv/www/WhatsAPI/src/php/whatsprot.class.php on line 1694". Could this be an error from the php version installed on my computer? 
Thank you for your answers :)

**Comment by d3ivys** [comment]
Hi Guys!!.. 
I am a new user and wanted to use WhatsAPI. I'm having some issues configuring the API. I can send messages, I can see the status of my contacts.. But I can't receive any messages. In the log file I get this error: Call to undefined method WhatsProt::pollMessages() in /var/www/testw/Chat-API-master/examples/ajaxDemo/socket.php on line 113.

In the ajax response I get this data and I think is an encrypted message:

tx  <auth mechanism="WAUTH-2" user="5076418xxxx">��d/50764182855���Z'�*���)0eIaL2�1442266328</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge> ��������`�Q������Y�</challenge>

tx  <response>`n딄�#� h����tcF#��b���a}s��</response>

rx  <success t="1442266351" props="4" kind="free" status="active" creation="1367025991" expiration="1456574001"> �!���i�x��Y 5s���</success>

tx  <presence name="0"></presence>

tx  <presence type="subscribe" to="5076747xxxx@s.whatsapp.net"></presence>

rx  <receipt from="5076747xxxx@s.whatsapp.net" type="read" offline="0" id="vH49GMs9KDD70" t="1442266350"></receipt>

tx  <ack to="5076747xxxx@s.whatsapp.net" class="receipt" id="vH49GMs9KDD70" type="read"></ack>

rx  <ib from="s.whatsapp.net">
rx    <offline count="1"></offline>
rx  </ib>

rx  <presence from="5076418xxxx@s.whatsapp.net"></presence>

rx  <presence from="5076747xxxx@s.whatsapp.net"></presence>

rx  <presence from="5076747xxxx@s.whatsapp.net"></presence>

rx  <chatstate from="5076747xxxx@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <message from="5076747xxxx@s.whatsapp.net" type="text" id="47qrjwhYG8Y2E6" t="1442266354" notify="Petiiii">
rx    <enc v="1" type="msg">3 !�[ޔ�B��j��� ��:��F,B3_�WtE`h"l� M�ni�]}"��Ge�_�q</enc>
rx  </message>

tx  <receipt type="read" to="5076747xxxx@s.whatsapp.net" id="47qrjwhYG8Y2E6"></receipt>

rx  <ack from="5076747xxxx@s.whatsapp.net" class="receipt" type="read" id="47qrjwhYG8Y2E6"></ack>

Thanks a lot.

**Comment by d3ibys** [comment]
Hi Guys!!.. 
I am a new user and wanted to use WhatsAPI. I'm having some issues configuring the API. I can send messages, I can see the status of my contacts.. But I can't receive any messages. In the log file I get this error: Call to undefined method WhatsProt::pollMessages() in /var/www/testw/Chat-API-master/examples/ajaxDemo/socket.php on line 113.

In the ajax response I get this data and I think is an encrypted message:

tx  <auth mechanism="WAUTH-2" user="5076418xxxx">��d/50764182855���Z'�*���)0eIaL2�1442266328</auth>

rx  <start from="s.whatsapp.net"></start>

rx  stream:features/stream:features

rx  <challenge> ��������`�Q������Y�</challenge>

tx  <response>`n딄�#� h����tcF#��b���a}s��</response>

rx  <success t="1442266351" props="4" kind="free" status="active" creation="1367025991" expiration="1456574001"> �!���i�x��Y 5s���</success>

tx  <presence name="0"></presence>

tx  <presence type="subscribe" to="5076747xxxx@s.whatsapp.net"></presence>

rx  <receipt from="5076747xxxx@s.whatsapp.net" type="read" offline="0" id="vH49GMs9KDD70" t="1442266350"></receipt>

tx  <ack to="5076747xxxx@s.whatsapp.net" class="receipt" id="vH49GMs9KDD70" type="read"></ack>

rx  <ib from="s.whatsapp.net">
rx    <offline count="1"></offline>
rx  </ib>

rx  <presence from="5076418xxxx@s.whatsapp.net"></presence>

rx  <presence from="5076747xxxx@s.whatsapp.net"></presence>

rx  <presence from="5076747xxxx@s.whatsapp.net"></presence>

rx  <chatstate from="5076747xxxx@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <message from="5076747xxxx@s.whatsapp.net" type="text" id="47qrjwhYG8Y2E6" t="1442266354" notify="Petiiii">
rx    <enc v="1" type="msg">3 !�[ޔ�B��j��� ��:��F,B3_�WtE`h"l� M�ni�]}"��Ge�_�q</enc>
rx  </message>

tx  <receipt type="read" to="5076747xxxx@s.whatsapp.net" id="47qrjwhYG8Y2E6"></receipt>

rx  <ack from="5076747xxxx@s.whatsapp.net" class="receipt" type="read" id="47qrjwhYG8Y2E6"></ack>

Thanks a lot.

**Comment by mgp25** [comment]
@d3ivys use https://github.com/WHAnonymous/Chat-API instead

It's updated, and there is a wiki with all the documentation

Regards

**Comment by d3ibys** [comment]
@mgp25 Thank you for your response!!..

I did downloaded the last update, but I still have the same issues. ='( Can you provide me the link to download? Thank you.

Note: I'm using the ajaxDemo at the example folder. 

I apologize for my english.

**Comment by iceherosubzero** [comment]
Hello, 

I too was trying to use ChatAPI for sending messages to whatsapp from php, but I had some errors when I uploaded and ran my php scripts on php version 5.3.3 on my server.
The first error was "Unexpected '[' in whatsprot.class.php on line 43" and when I uploaded to a later version of php 5.4.45 or later I got this output 

tx  stream:features/stream:features

tx  <auth user="91xxxxxxxxxx" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  stream:features/stream:features

rx  <challenge>ef26f0d79aa125f61303e290e4371da078af5854</challenge>

tx  <response>359f18fdea7af3396aadcffa49d7db7b6c23e19ba3b52f29332bc4d929ee6547382d43ee9e078d3778310c66ff49b5058fdc79ae2b46b93ef958db776e986d9b395365c65ba8da6f94ddf3e04005</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

but I can't understand what this means. and my server logs had log errors as below (Image attached)
![screen shot 2016-10-24 at 1 04 22 pm](https://cloud.githubusercontent.com/assets/4712184/19637027/7f223de6-99ea-11e6-9d13-8c57badd5ef6.png)

Can anybody please help me understand what does this mean and how to fix this errors.

Below is the php code I used for sending msg to my friend on whatsapp.

<code><?php
require_once ('src/whatsprot.class.php');
$username = "xxxxxxxxxxxx"; //Mobile Phone prefixed with country code so for india it will be 91xxxxxxxx
$password = "my password";
$w = new WhatsProt($username, 0, "msg title", true); //Name your application by replacing “WhatsApp Messaging”
$w->connect();
$w->loginWithPassword($password);
$target = 'receiver number'; //Target Phone,reciever phone
$message = 'Hello User !! This is a Tutorial for sending messages via php to WhatsApp Account';
$w->SendPresenceSubscription($target); //Let us first send presence to user
$w->sendMessage($target,$message ); // Send Message
echo "Message Sent Successfully";
?></code>

Thanks,
iceheros
