### ISSUE TITLE
New version, user agent, token

### ISSUE THREAD

**Issue by shrenikp** [venomous0x/WhatsAPI#450]
Hello,
 This config: 
const WHATSAPP_DEVICE = 'Android';                      // The device name.
    const WHATSAPP_VER = '2.10.750';                        // The WhatsApp version.
    const WHATSAPP_TOKEN = "30820332308202f0a00302010202044c.......f918064fd26e30a'; // Token used in request/registration code.
    const WHATSAPP_USER_AGENT = 'WhatsApp/2.10.750 Android/4.2.1 Device/GalaxyS3';//'WhatsApp/2.10.523 WP7/7.10.8858 Device/HTC-HTC-H0002';  // User agent used in request/registration code.

doesn't seem to work anymore. I am trying to register and get my password using /src/php/exampleRegister.php

Anyone know the new config ?

**Comment by kaank** [comment]
Hi,

Please change this class in whatsappapi.dll 

  class WaToken {
        public static string GenerateToken(string number) {
            string s = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1430860548912" + number;
            byte[] bytes = Encoding.ASCII.GetBytes(s);
            byte[] value = MD5.Create().ComputeHash(bytes);
            return BitConverter.ToString(value).Replace("-", string.Empty).ToLower();
        }
        private static List<byte> GetFilledList(byte item, int length) {
            List<byte> list = new List<byte>();
            for (int i = 0; i < length; i++) {
                list.Add(item);
            }
            return list;
        }
    }

Kaan Karataç

**Comment by Kram951** [comment]
Hi all,

I am testing Kaank code, and i get the following error: bad_token;
Anyone can suggest what is the issue?

**Comment by kaank** [comment]
Hi,

Download latest whatsapp dll , This dll is working on my project.

https://www.dropbox.com/s/5ua1x0gfianweqw/WhatsAppApi.dll?dl=0

Kaan Karataç

**Comment by mgp25** [comment]
Latest .dll is in here: https://github.com/mgp25/WART/tree/master/WART/Resources

**Comment by ramesh4321** [comment]
i got the error login failed:not authorized how to slove these error
