### ISSUE TITLE
Help setting up

### ISSUE THREAD

**Issue by ciph3rIT** [venomous0x/WhatsAPI#458]
I have been trying to setup WhatsAPI for the last 2 days.

On executing Whatsapp.php on remote web server ( PHP 5.3 ), I get the error

"Error: There was an error with the AJAX request. The request timed out.."

On Wamp

"Error: There was an error with the AJAX request. XML/Json format is bad."

My understanding is, I need these 4 parameters to be correctly updated:

1) My number ( Telephone number including the country code without '+' or '00' )

919971XXXXXX

2) Identity ( Obtained during registration with this API or using MissVenom (https://github.com/shirioko/MissVenom) to sniff from your phone.)

I couldn't get MissVenom to work with my Samsung S3 4.1. So I retrieved the identity with exampleRegister.php and WART

Both are different, which should I consider, since the string length is different for both?

From WART ( Digits changed for both, of course )
w%8a%a1%cd9%e2%f3%90%89%8c%83%e0g%re%ee%be%83%129%9a%99

From exampleRegister.php 
%da9%a2%ee%4ekk%0d2u%bf%ef%15%61%12%30%af%d8%07%09

3) Password: A server generated Password you received from WhatsApp. This can NOT be manually created

Extracted this from WART based on SMS received( Digits changed )

6Upo2iAM9ZnxIu2Ewy2hQ6eo2DM=

4) Nickname: This is the username (or nickname) displayed by WhatsApp clients.

I am entering my last username with Whatsapp.

EDIT: Also, when I run whatsapp.php , I get an error message on my phone. Whatsapp can only be used on device, please reverify the number

What am I doing wrong?

Thanks....

**Comment by Medanaresh** [comment]
hi, i am getting an error when i select the send message option i.e is   "Error: There was an error with the AJAX request. The request timed out.",  can you help me
