### ISSUE TITLE
Broadcast a text message to multiple phone numbers?

### ISSUE THREAD

**Issue by csinghgithub** [venomous0x/WhatsAPI#531]
Hi,

I have requirement to send message on whatsapp to multiple recipients may be in thousands. 

Please ans. my following questions?
1. Can i send text message to multiple recipients? or i have to broadcast that message to multiple recipients as i saw code snippet of SendBroadcastMessage in Issue #348?
1. If i have to broadcast a message then is there is any limit in broadcasting message to multiple recipients like 25 0r 30? because we have recipients list in thousands.
2. I have tried code snippet of SendBroadcastMessage in Issue #348 but didn't find classes/DLLs at following links:
   https://dl.dropboxusercontent.com/u/68235039/WhatsAppDLL.zip
   https://dl.dropboxusercontent.com/u/68235039/funxmpp.cs.txt
3. Can somebody provide me latest code and helper DLLs to broadcast message?

Thanks & Regards
Charanjot Singh

**Comment by patelchandresh** [comment]
WHAT'S UP SMS SOFTWARE VIA DESKTOP APPLICATION
https://drive.google.com/file/d/0B5zWD5aoDdVNRHp2czZuVTU1aXM/view?ts=568cf5c7

mob : 917359668270
pass : IQlNXscLKEO6bKONDoIGZM4keiI=
nickname : test

**Comment by mgp25** [comment]
SCAM, DO NOT USE IT
