### ISSUE TITLE
Channel Blocked

### ISSUE THREAD

**Issue by TruthEdge** [venomous0x/WhatsAPI#533]
Hello,

It seems that after recent download there is a big issue .

I'm sending to 13 Numbers , those 13 numbers have the Channel added on their contact list .
We are already using the API the a real client to send presence/ sync to contact which i'm sending to / send typing message/sending message/send presence un-available / channel disconnect .

Exactly after 6-9 numbers the Channel would be blocked from Whatsapp .

What is wrong with the new API ? we was working on this before and didn't faced any issue .

And Shiriko, Don't give me the spam lecture, i'm sending to 13 numbers & i do have the sending number pre-saved on all mobiles . 

What is going wrong ?

Regards

**Comment by HaroldoMaiolino** [comment]
Supplier Channel senders to Whatsapp
100% New
1,000 Channels - U $ 140.00
Special discount for large purchase
Immediate delivery
Skype=pantanartes1

Haroldo Maiolino
5567-9933-9151

**Comment by mohmedmostafa** [comment]
channels for whatsapp for salebegin with .$.26
Whastapprocket.com
whatsapprocket@gmail.com
