### ISSUE TITLE
How to get the password from WhatsApp server

### ISSUE THREAD

**Issue by JonZarate** [venomous0x/WhatsAPI#681]
As far as I know, the password was the same as the Wi-Fi mac of my iPhone. 

It seems that I need another password that my phone negotiated with the servers.

How can I get it ? I am stuck in the Login page.

Thank you

EDIT : The whatsapp.php file on the "tests" folder is giving me the following result:
# !/usr/bin/php

Notice: Undefined variable: argc in C:\XAMPP\htdocs\tests\whatsapp.php on line 26

Notice: Undefined index: argv in C:\XAMPP\htdocs\tests\whatsapp.php on line 27
USAGE: [-l] [-s ] [-i ] [-set ] phone: full number including country code, without '+' or '00' -s: send message -l: listen for new messages -i: interactive conversation with -set: Set Status to 

Do I need to worry about it ?

**Comment by hs4859** [comment]
can anyone plz tell me how to log in on whatsapp server

**Comment by AnandMamar** [comment]
@shirioko @JonZarate please provide me source code for getting password from WART because now its not working.
