### ISSUE TITLE
Last Seen 

### ISSUE THREAD

**Issue by JonZarate** [venomous0x/WhatsAPI#684]
I would like to get the Last Seen time of a WhatsApp user. 

What do I have to do ?

Do I have to add a listener to _onRequestLastSeen_ event ?

**Comment by bongbongjin** [comment]
hi sir.,
I am gonna to get last seen from many user.
How should i do?
I have aleady tried.. but it is not working fine now....
  string[] numbers;
                List<string> phonesublist = mValidlist.GetRange(i, step_cnt);
                numbers = phonesublist.Cast<string>().ToArray();
                wa.SendGetStatuses(numbers);
                for (int j = 0; j < step_cnt; j++)
                {
                    wa.SendPresenceSubscriptionRequest(numbers[j]);
                    
                    wa.SendGetServerProperties();
                    wa.SendQueryLastOnline(numbers[j]);
                    Thread.Sleep(10);
                }
This is my code.
At first it is working and after some minutesi would recieve error code 
<iq from="201000759252@s.whatsapp.net" id="last_9" type="error">
RECVD:   <error code="405" text="not-allowed"></error>
RECVD: </iq>
What s up?
Could you explain to help me?
thanks.

**Comment by mgp25** [comment]
@bongbongjin this is WhatsAPI (php), not yowsup (python), go to the proper repository.

Regards
