### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'Login Failure'

### ISSUE THREAD

**Issue by amrdesign** [venomous0x/WhatsAPI#751]
hello

when login Failure i see that error and script stop 

Fatal error: Uncaught exception 'Exception' with message 'Login Failure' in E:\xamp_amr\htdocs\server\@kw\custom\testy\whats\v1\live\class\whatsprot.class.php:1582 Stack trace: #0 E:\xamp_amr\htdocs\server\@kw\custom\testy\whats\v1\live\class\whatsprot.class.php(465): WhatsProt->doLogin() #1 E:\xamp_amr\htdocs\server\@kw\custom\testy\whats\v1\live\read.php(155): WhatsProt->loginWithPassword('560o9MSUCUU9gpe...') #2 {main} thrown in E:\xamp_amr\htdocs\server\@kw\custom\testy\whats\v1\live\class\whatsprot.class.php on line 1582

**Comment by dipen3492** [comment]
tx  <stream:features></stream:features>

tx  <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="WAUTH-2" user="919016023117"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>å!ûjâÅçLŽâË@ì|!</challenge>

tx  <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">º*¼\ÛÕ¸Aè€^©Ç%w±ámîM¢hë£§†sEÆx¤ô</response>


( ! ) Fatal error: Uncaught exception 'Exception' with message 'Login Failure' in D:\wamp\www\wp\WhatsAPI-master\src\whatsprot.class.php on line 1640
( ! ) Exception: Login Failure in D:\wamp\www\wp\WhatsAPI-master\src\whatsprot.class.php on line 1640
Call Stack
#	Time	Memory	Function	Location
1	0.0000	142984	{main}( )	..\test.php:0
2	0.0310	1644968	WhatsProt->loginWithPassword( )	..\test.php:14
3	0.0310	1645744	WhatsProt->doLogin( )	..\whatsprot.class.php:474
please help us to find perticular solution..

**Comment by dipen3492** [comment]
plese dont make us full... we will do whatever you were tell us but we all get same error so plese help us or give us right scripts..

**Comment by mgp25** [comment]
Do you read the comments? Use WhatsAPI Official

**Comment by dipen3492** [comment]
plz send full code my id and perfectlly work in my pc...

**Comment by mgp25** [comment]
@dipen3492 go to WhatsAPI Official

**Comment by dipen3492** [comment]
this not work proper

**Comment by dipen3492** [comment]
same error is up

**Comment by mgp25** [comment]
@dipen3492 you are not even setting a password!! go to WhatsAPI Official and read the wiki.

**Comment by dipen3492** [comment]
i  am paaword and id use to wart exe software

**Comment by dipen3492** [comment]
There was an error with the AJAX request. XML/Json format is bad.
this error create

**Comment by dipen3492** [comment]
what's happen? please reply me...

**Comment by dipen3492** [comment]
i found"Error: There was an error with the AJAX request. XML/Json format is bad."...so help me to slove it...

**Comment by realreef** [comment]
thx with this forum,  it`s work
