### ISSUE TITLE
userIdentity

### ISSUE THREAD

**Issue by xvilo** [venomous0x/WhatsAPI#794]
Hi,

I'm quite new in to the whatsapi... but what should my userIdentity be? 

The output is:
```php -f whatsapp_whatsapi_send.php "Warning: CPU temperature at 65°C"
tx  stream:features/stream:features

tx  <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="WAUTH-2" user="+31610608632"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  stream:features/stream:features

rx  <challenge>5????8??? ??9}???</challenge>

tx  <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">q??"N@f4P????]??PK?q?"?wqB?z?w</response>

Fatal error: Uncaught exception 'Exception' with message 'Login Failure' in /Volumes/ORCHID/Users/xvilo/whatsapp/WhatsAPI/src/php/whatsprot.class.php:1618
Stack trace:
#0 /Volumes/ORCHID/Users/xvilo/whatsapp/WhatsAPI/src/php/whatsprot.class.php(465): WhatsProt->doLogin()
#1 /Volumes/ORCHID/Users/xvilo/whatsapp/whatsapp_whatsapi_send.php(13): WhatsProt->loginWithPassword('aab0c39d826955f...')
#2 {main}

  thrown in /Volumes/ORCHID/Users/xvilo/whatsapp/WhatsAPI/src/php/whatsprot.class.php on line 1618

```

and my credentials are:
```

$userPhone        = '+3161**_8632'; 
$userIdentity     = '+3161**_8632';
$userName         = 'Pois0n'; 
$password         = 'aab0c39d***************558e01faffd10d1af4'; 
$debug            = true;

```

What did i do wrong :o 

Thanks in advance,

//Sem
```

**Comment by karlmendes** [comment]
Hi there, i follow the steps and can send any messages with 'test' but before a little time, the whatts appear block my connections:

[] Logging in as 'Karl' (55xxxxxxxx)
tx  <stream:features></stream:features>

tx  <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="WAUTH-2" user="55xxxxxx">��@R55xxxxxxxxxx,��%mq%�Q�KQq��3��.�1426125977WhatsApp/2.11.378 Android/4.3 Device/GalaxyS3 MccMnc/724001</auth>

PHP Fatal error:  Uncaught exception 'Exception' with message 'Login Failure' in /Projetos/Exemplos_net/whatsprot.class.php:1640
Stack trace:
#0 /Projetos/Exemplos_net/whatsprot.class.php(474): WhatsProt->doLogin()
#1 /Projetos/Exemplos_net/whatsapp.php(46): WhatsProt->loginWithPassword('Kzfv6L3VSwkxw33...')
#2 {main}
  thrown in /Projetos/Exemplos_net/whatsprot.class.php on line 1640


Anyone can help me ?

**Comment by Pituky** [comment]
It seems you are blocked.

**Comment by karlmendes** [comment]
I think this too, after a more little time, the command sending again

**Comment by Pituky** [comment]
Yes in general the blocks seems to be temporary, not sure if they blocks accounts permanently.

**Comment by karlmendes** [comment]
Hopefully never hahahahhaa

thx a lot !!

**Comment by karlmendes** [comment]
Hi all again, anyone know a method to configure the whatts in cel and in whatsAPI conf  ?
