### ISSUE TITLE
contactsync.php always returns Error: Received unknown response: 

### ISSUE THREAD

**Issue by jammy666** [venomous0x/WhatsAPI#817]
im using contactsync.php with following params but it always returns 

Error: Received unknown response: 

91 is my country code

contactsync.php?phone=91myLoggedNumber&pass=PasswordHere&u[]=+91numberToCheck

this is the code i have

require_once "contacts.php";
$username = @$_GET["phone"];
if ($username == null || empty($username)) {
    die("Missing param: phone");
}

$password = @$_GET["pass"];
if ($password == null || empty($password)) {
    die("Missing param: pass");
}

$debug = true;

$contacts = @$_GET["u"];
if ($contacts == null || empty($contacts)) {
    die("Missing param: u[]");
}

try {
    $sync = new WhatsAppContactSync($username, $password, $contacts, $debug);
    echo $res = $sync->executeSync();
} catch (Exception $e) {
    die("Error: " . $e->GetMessage());
}

foreach ($res as $contact) {
    var_dump($contact);
}

please let me know what im doing wrong

**Comment by amol9supe** [comment]
hello sir,
please check image.
![untitled](https://cloud.githubusercontent.com/assets/3205314/10902306/ca4c1904-8221-11e5-94a1-44af786916d6.png)
