### ISSUE TITLE
How to get last seen

### ISSUE THREAD

**Issue by JonZarate** [venomous0x/WhatsAPI#827]
Hi !
It's been a long time since I last used this project but I want to put my hands on it again. I was trying to get the last seen time of a number but I wasn't successful. 

To be honest, my plan was/is to use this PHP code to create a Java application to use WhatsApp. This way I will improve my Java skills and learn PHP ( and also how to link them in the same project ). 

First of all, I want to understand the code the best as I can but there are so many files, what developping application do you use to edit the whole project ? Do you use eclipse ? Can I import the whole code into a project in eclipse ? 

I think that's enough for now. Thanks in advanced !

**Comment by bongbongjin** [comment]
Hi sir.
how many could i get get last seen informationg at once?
I have tested about that.
At the beginning it has been working fine.
But after i got hundreds informations, i had got only <error code="404" text="item-not-found"></error>.
What s up?!
I had got only <error code="40" text="item-not-found"></error> continuesly.
So i had tested again after some mins.
Then i could got correct last seen information again. and after mins, same error are occured.
Please help me.

**Comment by bongbongjin** [comment]
Adding comment.
I am trying to get so much last seen informations.
How could i do?!!

**Comment by mgp25** [comment]
Use WhatsAPI Official, this repo is inactive. Read the wiki, everything its explained there: https://github.com/venomous0x/WhatsAPI/wiki

**Comment by mhamzas** [comment]
@JonZarate can you please elaborate how you make it work ?

**Comment by bongbongjin** [comment]
thanks for your reply.
if i d like to get last seens informaion for so much phone number. 
how should i do?Thanks.
bong
5/5/2015 3:39 AM mhamzas (notifications@github.com) 

  @JonZarate 
  can you please elaborate how you make it work ?
  —Reply 
  to this email directly or view 
  it on GitHub.

**Comment by mhamzas** [comment]
you can add lines with different targets

$w->sendGetRequestLastSeen($dst1);
$w->sendGetRequestLastSeen($dst2);
$w->sendGetRequestLastSeen($dst3);

**Comment by bongbongjin** [comment]
Thanks
But how many number could i check ?
i have already tried using this way.
But after checking hundreds numbers , and last seen would not be recieved 
for a while.
thanks.5/5/2015 3:31 PM mhamzas (notifications@github.com) 

  you can add lines with different targets
  $w->sendGetRequestLastSeen($dst1);$w->sendGetRequestLastSeen($dst2);$w->sendGetRequestLastSeen($dst3);
  —Reply 
  to this email directly or view 
  it on GitHub.

**Comment by mhamzas** [comment]
I don't know about it. I think there would be something. try using sleep()
method
